declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';

  type IconProps = SVGProps<SVGSVGElement> & {
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
    className?: string;
  };

  type Icon = FC<IconProps>;

  export const Package: Icon;
  export const MapPin: Icon;
  export const CheckCircle2: Icon;
  export const Circle: Icon;
  export const Truck: Icon;
  export const Plane: Icon;
  export const Search: Icon;
  export const Shield: Icon;
  export const Leaf: Icon;
  export const Zap: Icon;
  export const Warehouse: Icon;
  export const Ship: Icon;
  export const Factory: Icon;
  export const ShoppingBag: Icon;
  export const Boxes: Icon;
  export const Mail: Icon;
  export const Phone: Icon;
  export const Clock: Icon;
  export const Globe: Icon;
  export const ArrowRight: Icon;
  export const Check: Icon;
  export const X: Icon;
  export const Menu: Icon;
  export const XCircle: Icon;
  export const AlertCircle: Icon;
  export const Info: Icon;
  export const HelpCircle: Icon;
  export const ChevronRight: Icon;
  export const ChevronDown: Icon;
  export const ChevronUp: Icon;
  export const ChevronLeft: Icon;
  export const MoreHorizontal: Icon;
  export const MoreVertical: Icon;
  export const Plus: Icon;
  export const Minus: Icon;
  export const Trash: Icon;
  export const Edit: Icon;
  export const Copy: Icon;
  export const Download: Icon;
  export const Upload: Icon;
  export const ExternalLink: Icon;
  export const Link: Icon;
  export const Unlink: Icon;
  export const Refresh: Icon;
  export const RotateCcw: Icon;
  export const RotateCw: Icon;
  export const Play: Icon;
  export const Pause: Icon;
  export const Square: Icon;
  export const CircleDot: Icon;
  export const Users: Icon;
  export const Award: Icon;
  export const Rocket: Icon;
  export const MessageSquare: Icon;
  export const MessageCircle: Icon;
  export const Recycle: Icon;
  export const Wind: Icon;
  export const Calendar: Icon;
  export const CreditCard: Icon;
  export const Briefcase: Icon;
  export const Facebook: Icon;
  export const Twitter: Icon;
  export const Linkedin: Icon;
  export const Youtube: Icon;
  export const Instagram: Icon;
  export const ChevronDownIcon: Icon;
  export const ChevronLeftIcon: Icon;
  export const ChevronRightIcon: Icon;
  export const ArrowLeft: Icon;
  export const GripVertical: Icon;
  export const PanelLeft: Icon;

  export default Icon;
}
